### ISSUE TITLE
Add rounding support

### ISSUE THREAD

**Issue by osos** [olahellgren/home-assistant-sensor-widget-scriptable#2]
Sometimes sensor values have loads of digits which does not provide any value for the human eye (e.g. solar production 3.122999 kW)

How can we add a rounding feature to set how many decimals the sensors should show?

**Comment by olahellgren** [comment]
Rounding is out of scope for this plugin. The thought is to have it as simple as possible. If you want a nice rounded sensor value you should create template sensor, like below:

```yaml
template:
  - unique_id: el_price_dishwasher_short
    sensor:
      - name: "Diskmaskin (Snabb)"
        unit_of_measurement: "kr"
        state: >
          {{ (1.30 * states.sensor.nordpool_kwh_se3_sek_3_095_025.state|float) | round(2) }} 
```
